# -*- coding: utf-8 -*-
"""Estruturas de repetição

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-rx_6zvWmscsRHW3Sxyjku7kKf6G2xH1

**Estruturas de repetição**

# **1.** Crie um programa no qual o usuário informe 2 números inteiros: a e b. Para que o programa continue sua execução, verifique se a < b. Se sim, calcule a soma dos números inteiros no intervalo [a, b]. Caso contrário, informe uma mensagem de erro.
"""

#entrada de dados
a=int(input("seu numero aqui:"))
b=int(input("seu outro numero aqui:"))
soma = 0
#processamento de dados
if a<b:
  for i in range(a+1,b):
    soma += i
  #saída de dados
  print(soma)
else:
  print("Erro")



"""(#entrada de dados)Primeiro pedimos ao usuário que insira os valores que serão utilizados, que nesse caso, precisam ser números inteiros, e atribuímos a variável "a" e "b" respectivamente. (#processamento de dados) Após isso criamos um condicional onde: se "a"(primeiro número) for menor que "b"(segundo número), poderemos dar início aos passos seguintes. Nesse exemplo, foi utilizada a estrutura "for". Na linha 6,  (#saida de dados)Assim obtemos o resultado de acordo com os números informados."""

#entrada de dados
a=int(input("seu numero aqui:"))
b=int(input("seu outro numero aqui:"))
soma = 0
#processamento de dados
if a<b:
  i = a+1
  while i < b:
    soma += i
    i += 1
  #saída de dados
  print(soma)
else:
  print("Erro")

"""# 2.Um professor de Matemática deseja construir um programa para gerar uma Progressão Aritmética (PA). Para isso, devem ser informados 3 argumentos:
# a) primeiro termo
# b) quantidade de termos
# c) razão.
"""

#entrada de dados
pr=int(input("insira o primeiro termo:"))
nt=int(input("insira o numero de termos da sequência:"))
rz=int(input("insira a razão entre termos:"))
#processamento de dados
for i in range(pr,nt*rz+pr,rz):
  #saída de dados
  print(i,end=" ")

"""primeiro, iremos pedir para o usuário colocar as três informações necessarias para realizar o calculo. Esta parte está logo abaixo da entrada de dados.
depois, colocamos o for para repetir um comando, o I será apenas uma variável não importante. O in range tem como objetivo determinar de quanto a quanto a variavel I irá variar. Dentro, nós temos os valores pedidos pelo programa, que serão utilizados para dizer: 1-PR= Onde a progressão irá começar, nt*rz+pr= Aonde a progressão irá terminar, e RZ é quanto cada termo terá de espaço entre eles. Por fim, colocamos a variavel I para ser printada pelo programa, e com um end, que irá colocar um

# 3.Construa um programa que receba o nome e o preço de 5 medicamentos de uma drogaria (considere que o usuário informou cinco medicamentos distintos). O programa deve informar o nome e o preço do medicamento mais barato, bem como a média aritmética dos preços informados.
"""

#declaração de variaveis/listas
remedio=[]
preço=[]
#entrada de dados e indexação
for i in range(0,5):
  remedio.append(input(f"nome do {i+1}° remédio: "))
  preço.append(int(input(f"preço do {i+1}° remédio: ")))
#processamento dos dados e saída
a = preço.index(min(preço))
print("O NOME DO REMEDIO MAIS ACESSIVEL:",remedio[a])
print("SEU PREÇO DE REMEDIO É:",min(preço))
#complemento da média
media=0
for i in range(0,5):
	media += preço[i]
media = media/5
print("A MÉDIA DOS PREÇOS É:",media)

"""primeiro, devemos declarar as variáveis, que nesse caso serão as listas remédio e preço, que serão responsáveis por armazenar os valores que serão inputados pelo usuário (#declaraçao de variáveis)

depois, iremos pedir ao usuário o valor e o nome dos remédios que ele deseja saber qual é mais barato e a sua média. Para realizar isso, devemos utilizar o comando for e o in, que irão repetir os processos dentro deles cinco vezes, como especificado nesta parte: range(0,5). Dentro do comando for, iremos escrever o comando que será responsavel por pedir ao usuário o input dos remédios e de seus preços, que será adicionado à sua lista pertencente (remédio será adicionado a lista de remedio e preço será adicionado á lista de preço). Também utilizamos o comando .append, que irá adicionar o item inputado ao final da lista.(#entrada de dados)

após isso, utilizamos de uma variavel qualquer para armazenar a posição do menor preço, que será obtido através do comando .index(min()).(#processamento de dados)

depois, iremos printar o valor do item com menor preço pela variavel "A", que irá chamar o valor da variavel de menor preço e será utilizado para achar o seu correspondente na lista remédios. Exemplo: Se o menor valor de preço é pertencente ao numero imputado em 3 indice, a variavel "A" irá absorver o indice do preço, que irá ser utilizada para chamar o valor correspondente. A variavel "A" também será utilizada para chamar o indice correspondente na lista de nomes de remédios. Já que o preço em posição 3 será correspondente ao remédio imputado na posição 3 na lista de nomes.(#saída de dados)

finalmente, utilizamos dos valores imputados em preço que serão absorvidos pela lista de preços para o calculo da média aritmética, que será o valor somado de todos os itens divido pela quantidade de itens, que sempre será 5, ou seja, se imputarmos n1,n2,n3,n4,n5, nós teremos (n1+n2+n3+n4+n5)/5.  que é a média que será printada(#complemento da midia)

# 4.Imagine um sistema de caixa eletrônico. Construa um programa que receba a senha de um correntista para validar o seuacesso ao sistema. Considere que a senha fictícia do correntistaé 123456. Considere as seguintes restrições:

# • quando a senha estiver correta, mostrar a mensagem:
# “Olá, <SEUNOME>. Seja bem-vindo ao nosso banco!"

# • quando o usuário errar a senha pela primeira vez, mostrar a mensagem:
# “Senha incorreta! Você ainda tem 2 tentativas.”

# • se o usuário errar a senha pela segunda vez, mostrara mensagem:
# “Senha incorreta! Você ainda tem 1 tentativa.”

# • se o usuário errar a senha novamente, mostrar a mensagem
# “Sua senha foi bloqueada! Por favor, dirija-se a um de nossos caixas.” e o programa deve ser encerrado.
"""

#antes do For:
senha = 123456
digit = int(input("Digite sua senha: "))
#execução do for:
for i in range(2,-1,-1):
  if digit == senha:
    print("Olá, Waldisney. Seja bem vindo ao nosso banco!")
    break
 #verificação se o valor de I utilizado em For é 0:
  elif i != 0:
    print(f"Senha incorreta! Você ainda tem {i} tentativas.")
    digit = int(input("Digite sua senha: "))
  else:
    print("Sua senha foi bloqueada! Por favor, dirija-se a um de nossos caixas.")

"""Neste exercicio, iremos utilizar o for para repetir o numero de vezes que o usuário pode inserir a senha em 3 vezes. Após o uso das 3 vezes, o valor de I será de 0, que o programa irá reconhecer para encerrar o programa.

No inicio, nós temos apenas a senha já definida no sistema e o pedido de input para o usuário inserir a senha. Após a primeira inserção da senha, o programa irá verificar se o valor inserido pelo usuário é equivalente ao valor já pré-definido da senha. Caso o valor seja igual, o programa irá printar a mensagem: "olá, waldisney, seja em vindo ao nosso banco!". Caso contrário, o programa irá utilizar o comando For com a variável "I", que terá no começo o valor de 2 com variação de -1 a cada vez que o programa for repetido.(execução do for:)

Em todas as vezes que o programa for repetido pelo for, nós teremos um código que irá verificar o valor de "I", que será de inicialmente 2 e diminuido em 1 a cada vez que o usuário erra a senha. Quando o valor de "I" for de 0, o programa irá realizar apenas o comando de printar a mensagem:"Sua senha foi bloquada! Por favor, dirija-se a um de nossos caixas.". Após o término dessa mensagem, o programa não realizará mais nenhuma ação, assim automaticamente terminando o programa.

# 6.Construa um programa que receba uma lista contendo a estatura dos alunos de uma escola. Crie um relatório que informe a:

#    a. menor estatura

#    b. maior estatura

#    c. média das estaturas informadas
"""

x=int(input("quantas alturas serão informadas:"))
alturas=[]
for i in range(0,x,1):
  alturas.append(int(input("diga a altura:")))
print("sua maior altura é:",max(alturas))
print("sua menor altura é:",min(alturas))
print("sua média de altura é:",sum(alturas)/x)

"""nós começamos pedindo ao usuário o número de alturas que serão informadas, esse número será a variavel X.
Após isso, declaramos a lista Alturas=[], que será utilizada para armazenar os valores informados. O valor será informado X vezes, pois foi o número que o usuário disse que serão de alturas diferentes.
Após isso, apenas precisamos utilizar o comando Max, min e sum, que serão, respectivamente: valor mais alto na lista alturas, valor mais baixo na lista alturas e a soma de todos os valores contidos em altura. Utilzaremos novamente o X para dividir a soma dos valores de altura, já que a média aritmética é dada pela soma dos valores divida pela quantidade de valores na lista.
"""