# -*- coding: utf-8 -*-
"""Exercícios de Estrutura Sequencial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Foujyl4adtqJePIsRVf7zWFPA_S5V17v

**Exercícios de Estrutura Sequencial**

1. Um aluno iniciou seus estudos em geometria plana e, para
validar se suas respostas estão corretas, solicitou sua ajuda. Sabendo que *área triangulo = (base*altura)/2*, construa um programa para
auxiliar esse aluno.
"""

#entrada de dados
base = float(input())
altura = float(input())
area = float()
#processamento de dados
area = (base*altura)/2
#saida de dados
print(area)

"""(#entrada de dados)Primeiro pedimos ao usuário que insira os valores que serão utilizados no cálculo da área do triângulo. (#processamento de dados) Com base nesses valores, utilizamos a fórmula: área do triangulo = (base*altura)/2.(#saida de dados)Assim obtemos o resultado de acordo com os números informados.

**2.** Agora o mesmo aluno precisa que você construa um programa para calcular o comprimento de uma circunferência. Para
isso, o aluno informará ao programa o raio da circunferência.
Sabe-se que Comprimento = 2* pi *raio.
"""

#entrada de dados
raio = float(input())
cir = float()
pi = 3.14
#processamento de dados
cir = 2*pi*raio
#saída de dados
print(cir)

"""(#entrada de dados)Primeiro pedimos ao usuário que insira os valores que serão utilizados no cálculo do comprimento de uma circunferência.(#processamento de dados) Com base nesses valores, utilizamos a fórmula: Comprimento = 2* pi *raio. (#saida de dados) A partir desse cálculo obtemos o resultado de acordo com os números informados.

**3.** Construa um programa que leia 2 números reais informados
pelo usuário. Ao fim, o programa deve calcular e imprimir:
a. a soma dos dois valores
b. o produto entre eles
"""

#entrada de dados
a = int(input('insira um valor:'))
b = int(input('insira um valor:'))
#processamento de dados
soma = a + b
produto = a * b
#saída de dados
print('a soma dos valores é:', soma )
print('o produto dos valores é:', produto)

"""(#entrada de dados)Primeiro pedimos ao usuário que insira os valores que serão utilizados, nesse caso, precisam ser dois números reais.(#processamento de dados) Com base nesses valores, utilizamos a fórmula: Comprimento = 2* pi *raio.(#saida de dados) A partir disso, obtemos o resultado de acordo com os números informados.

**4.** Implemente um programa que converta o valor de uma velocidade média em km/h para m/s. Para isso, o usuário deve

informar o valor da velocidade média. Sabe-se que o fator utili-
zado para essa conversão é 3,6.
"""

#entrada de dados
kh = float(input())
#processamento de dados
ms = kh / 3.6
#saída de dados
print(ms)

"""(#entrada de dados)Primeiro pedimos ao usuário que insira os valores que serão utilizados, que nesse caso, é o valor da velocidade média. (#processamento de dados) Com base nesses valores, convertemos o número informado utilizando o fator 3,6; obtendo a fórmula: ms = kh / 3.6.(#saida de dados)Após o processamento, temos a impressão do resultado de acordo com os números informados."""